version: '3.1'

services:
  nginx-server:
    image: nginx:1.15
    container_name: nginx_container
    volumes:
#      - ./:/prod-app
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
#    networks:
#      - my-network
    depends_on:
      - flask_app
  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: flask_container
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 "app.wsgi:app"

#    volumes:
#      - ./:/prod-app
#    networks:
#      my-network:
#        aliases:
#          - flask-app
#
#networks:
#  my-network: